basePath: /
host: localhost:8000
info:
  contact: {}
  description: API server for rock-paper-scissors game
  title: ro-pa-sci API
  version: "1.0"
paths:
  /user:
    post:
      parameters:
      - in: formData
        name: login
        type: string
      - in: formData
        name: password
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            type: object
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: session
    type: apiKey
swagger: "2.0"
